### PR TITLE
(feature) update mouse position clipping by using left and right width of blocks

### PR DESCRIPTION
**Pull request by zhehaoli1999**
Fix the bug of Tetris blocks getting out of boundary with invalid mouse positions.

### CODE REVIEW

**Comment by zhehaoli1999** [comment]
Before 👇
problem

After 👇
video

**Comment by zhehaoli1999** [comment]
Update and fix a bug. 
line 254
```python
if mouse[0] + r > right_edge 

-->  if mouse[0] + r > right_edge * 2
```

**Comment by zhehaoli1999** [comment]
Update mouse position clipping for rotation and the final result is shown as the gif above.

**Review by yuanming-hu — APPROVED** [review]
Awesome! Thanks :-)

**Pull request merged**
